[versions]
jackson = "2.16.0"
log4j = "2.22.0"

[libraries]
log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }

[bundles]
jackson = ["jackson-databind"]
log4j-runtime = ["log4j-core", "log4j-slf4j"]
